---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: karlkfi/concourse-dcind

params:
  FAUNA_ROOT_KEY:
  FAUNA_ENDPOINT:
  FAUNA_REPO_PASSWORD:

inputs:
  - name: fauna-go-repository

run:
  path: entrypoint.sh
  args:
    - bash
    - -ceu
    - |
      docker login -u _json_key -p "$FAUNA_REPO_PASSWORD" https://gcr.io > /dev/null 2>&1
      # start containers
      docker-compose -f fauna-go-repository/concourse/tasks/integration.yml run tests-17
      # stop and remove containers
      docker-compose -f fauna-go-repository/concourse/tasks/integration.yml down
      # remove volumes
      docker volume rm $(docker volume ls -q)
