version: "3.3"

services:
  faunadb:
    image: fauna/faunadb
    container_name: faunadb
    healthcheck:
      test: ["CMD", "curl" ,"http://faunadb:8443/ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  tests:
    environment:
      - FAUNA_ROOT_KEY
      - FAUNA_ENDPOINT
    image: golang:1.16.4-alpine3.13
    container_name: mytests
    depends_on:
      - faunadb
    volumes:
      - "../../:/tmp/app"
    working_dir: "/tmp/app"
    command:
      - concourse/scripts/integration-tests.sh
